// Code generated by phonearea-gen. DO NOT EDIT.
package phonearea

func PhoneTemplate(countryCode string) string {
	switch countryCode {

	case "ME":
		return "+382########"

	case "SD":
		return "+249########"

	case "IN":
		return "+91#########"

	case "UA":
		return "+380########"

	case "RO":
		return "+40#########"

	case "LA":
		return "+856########"

	case "BE":
		return "+32#########"

	case "GP":
		return "+590########"

	case "PL":
		return "+48#########"

	case "CI":
		return "+225########"

	case "EC":
		return "+593########"

	case "NZ":
		return "+64#########"

	case "DZ":
		return "+213########"

	case "UY":
		return "+598########"

	case "SY":
		return "+963########"

	case "BF":
		return "+226########"

	case "GR":
		return "+30#########"

	case "EH":
		return "+212########"

	case "CR":
		return "+506########"

	case "PF":
		return "+689########"

	case "TZ":
		return "+255########"

	case "YT":
		return "+262########"

	case "HR":
		return "+385########"

	case "MD":
		return "+373########"

	case "PH":
		return "+63#########"

	case "CD":
		return "+243########"

	case "TV":
		return "+688########"

	case "VA":
		return "+379########"

	case "NI":
		return "+505########"

	case "CK":
		return "+682########"

	case "BT":
		return "+975########"

	case "LK":
		return "+94#########"

	case "CH":
		return "+41#########"

	case "CM":
		return "+237########"

	case "GT":
		return "+502########"

	case "FR":
		return "+33#########"

	case "NP":
		return "+977########"

	case "RE":
		return "+262########"

	case "GQ":
		return "+240########"

	case "GA":
		return "+241########"

	case "MN":
		return "+976########"

	case "TW":
		return "+886########"

	case "LS":
		return "+266########"

	case "BH":
		return "+973########"

	case "CU":
		return "+53#########"

	case "KE":
		return "+254########"

	case "KR":
		return "+82#########"

	case "TK":
		return "+690########"

	case "CL":
		return "+56#########"

	case "KM":
		return "+269########"

	case "KI":
		return "+686########"

	case "SI":
		return "+386########"

	case "LI":
		return "+423########"

	case "IQ":
		return "+964########"

	case "SZ":
		return "+268########"

	case "PT":
		return "+351########"

	case "CX":
		return "+61#########"

	case "SK":
		return "+421########"

	case "TG":
		return "+228########"

	case "CY":
		return "+357########"

	case "GB":
		return "+44#########"

	case "PG":
		return "+675########"

	case "MW":
		return "+265########"

	case "CZ":
		return "+420########"

	case "MC":
		return "+377########"

	case "NL":
		return "+31#########"

	case "VU":
		return "+678########"

	case "NC":
		return "+687########"

	case "TL":
		return "+670########"

	case "PK":
		return "+92#########"

	case "KZ":
		return "+7##########"

	case "AE":
		return "+971########"

	case "SR":
		return "+597########"

	case "YE":
		return "+967########"

	case "TR":
		return "+90#########"

	case "LT":
		return "+370########"

	case "RU":
		return "+7##########"

	case "GN":
		return "+224########"

	case "IT":
		return "+39#########"

	case "MA":
		return "+212########"

	case "GI":
		return "+350########"

	case "FK":
		return "+500########"

	case "CO":
		return "+57#########"

	case "KW":
		return "+965########"

	case "BO":
		return "+591########"

	case "TM":
		return "+993########"

	case "IL":
		return "+972########"

	case "MF":
		return "+590########"

	case "AL":
		return "+355########"

	case "BG":
		return "+359########"

	case "MT":
		return "+356########"

	case "DE":
		return "+49#########"

	case "MX":
		return "+52#########"

	case "KG":
		return "+996########"

	case "SM":
		return "+378########"

	case "BQ":
		return "+599########"

	case "ML":
		return "+223########"

	case "MH":
		return "+692########"

	case "AZ":
		return "+994########"

	case "FM":
		return "+691########"

	case "BI":
		return "+257########"

	case "MO":
		return "+853########"

	case "FI":
		return "+358########"

	case "MZ":
		return "+258########"

	case "BL":
		return "+590########"

	case "TJ":
		return "+992########"

	case "MQ":
		return "+596########"

	case "SJ":
		return "+47#########"

	case "PY":
		return "+595########"

	case "EE":
		return "+372########"

	case "KP":
		return "+850########"

	case "TO":
		return "+676########"

	case "DK":
		return "+45#########"

	case "UM":
		return "+1##########"

	case "LU":
		return "+352########"

	case "IS":
		return "+354########"

	case "SO":
		return "+252########"

	case "ZW":
		return "+263########"

	case "MG":
		return "+261########"

	case "AU":
		return "+61#########"

	case "ZM":
		return "+260########"

	case "CA":
		return "+1##########"

	case "KH":
		return "+855########"

	case "BR":
		return "+55#########"

	case "PS":
		return "+970########"

	case "SB":
		return "+677########"

	case "MK":
		return "+389########"

	case "BZ":
		return "+501########"

	case "VN":
		return "+84#########"

	case "AR":
		return "+54#########"

	case "IE":
		return "+353########"

	case "ST":
		return "+239########"

	case "LR":
		return "+231########"

	case "BY":
		return "+375########"

	case "PE":
		return "+51#########"

	case "NU":
		return "+683########"

	case "SL":
		return "+232########"

	case "SG":
		return "+65#########"

	case "US":
		return "+1##########"

	case "BA":
		return "+387########"

	case "HT":
		return "+509########"

	case "CV":
		return "+238########"

	case "TN":
		return "+216########"

	case "MU":
		return "+230########"

	case "NR":
		return "+674########"

	case "CN":
		return "+86#########"

	case "ET":
		return "+251########"

	case "LB":
		return "+961########"

	case "TD":
		return "+235########"

	case "SN":
		return "+221########"

	case "ID":
		return "+62#########"

	case "JP":
		return "+81#########"

	case "UZ":
		return "+998########"

	case "SS":
		return "+211########"

	case "TH":
		return "+66#########"

	case "GL":
		return "+299########"

	case "PN":
		return "+870########"

	case "UG":
		return "+256########"

	case "MV":
		return "+960########"

	case "RW":
		return "+250########"

	case "GM":
		return "+220########"

	case "OM":
		return "+968########"

	case "SE":
		return "+46#########"

	case "CF":
		return "+236########"

	case "AF":
		return "+93#########"

	case "AW":
		return "+297########"

	case "PW":
		return "+680########"

	case "ZA":
		return "+27#########"

	case "FO":
		return "+298########"

	case "QA":
		return "+974########"

	case "BD":
		return "+880########"

	case "BN":
		return "+673########"

	case "PA":
		return "+507########"

	case "NE":
		return "+227########"

	case "ER":
		return "+291########"

	case "IO":
		return "+246########"

	case "NO":
		return "+47#########"

	case "NA":
		return "+264########"

	case "GW":
		return "+245########"

	case "GH":
		return "+233########"

	case "HK":
		return "+852########"

	case "PM":
		return "+508########"

	case "HN":
		return "+504########"

	case "SH":
		return "+290########"

	case "NF":
		return "+672########"

	case "WF":
		return "+681########"

	case "BJ":
		return "+229########"

	case "GF":
		return "+594########"

	case "JO":
		return "+962########"

	case "AD":
		return "+376########"

	case "SA":
		return "+966########"

	case "MM":
		return "+95#########"

	case "MY":
		return "+60#########"

	case "SX":
		return "+599########"

	case "SV":
		return "+503########"

	case "VE":
		return "+58#########"

	case "CC":
		return "+61#########"

	case "CG":
		return "+242########"

	case "AT":
		return "+43#########"

	case "HU":
		return "+36#########"

	case "NG":
		return "+234########"

	case "MR":
		return "+222########"

	case "LV":
		return "+371########"

	case "DJ":
		return "+253########"

	case "GY":
		return "+592########"

	case "GE":
		return "+995########"

	case "ES":
		return "+34#########"

	case "FJ":
		return "+679########"

	case "BW":
		return "+267########"

	case "RS":
		return "+381########"

	case "AO":
		return "+244########"

	case "LY":
		return "+218########"

	case "IR":
		return "+98#########"

	case "AM":
		return "+374########"

	case "WS":
		return "+685########"

	case "EG":
		return "+20#########"

	case "CW":
		return "+599########"

	case "SC":
		return "+248########"

	default:
		return "+7#########"
	}
}
